sudo: required
services:
  - docker

before_install:
  - docker build -t jagana/docker-react -f Dockerfile.dev .

script:
  - docker run jagana/docker-react npm run test -- --coverage
# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-react"
#   env: "docker-react-env"
#   bucket_name: "s3 bucket_name"
#   bucket_path: "docker-react"
#   on:
#     branch: master
